artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://raw.githubusercontent.com/tanux22/Wine-Grade-Estimator/main/winequality-data.zip
  # source_url: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  local_data_file: artifacts/data_ingestion/winequality-red.zip
  unzip_dir: artifacts/data_ingestion
  unziped_data_file: artifacts/data_ingestion/winequality-red.csv
  source_url: https://raw.githubusercontent.com/tanux22/Wine-Grade-Estimator/main/winequality-data.zip